# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomies', '0002_auto_20170330_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to=b''),
        ),
    ]
