# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomies', '0005_imglayout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgLayout',
        ),
    ]
